@include('admin.layouts.partials.styles')
@include('admin.layouts.partials.header')
@include('admin.layouts.partials.sidebar')
@yield('content')
@include('admin.layouts.partials.footer')
@include('admin.layouts.partials.scripts')
